name: soundboard
description: Flutter Soundboard

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sound: ^1.3.7
  shared_preferences: ^0.5.1+2
  uuid: ^2.0.1
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: MajorMonoDisplay
      fonts:
        - asset: fonts/MajorMonoDisplay-Regular.ttf
          style: normal